### ISSUE TITLE
Encrypted NZB

### ISSUE THREAD

**Issue by wheaten** [spotnet/spotnet#29]
Hoi,

We zien nu bij meerdere releases dat men gebruikt maakt van gecodeerde NZB's die via een externe weblink zijn op te halen. Is het mogelijk om deze te checken en indien aanwezig op de functie van NZB downloaden in te grijpen?

Spot plaatst externe weblink, weblink verwijst door naar een NZB-index, vervolgens deze NZB laden, hernoemen naar de title van de spot en in de queue van Sabnzbd plaatsen?
Ik heb dit nu via een omweg in een aantal Thema's voor spotnet gebruikt, maar kan dit standaard geïntegreerd worden in Spotnet?

De regex: 

``` php
var regex = /<A onfocus=(.*) title=(.*) (href="link:http:\/\/base64.derefer.me(.*)"|href="link:http:\/\/alturl.com(.*)")>(.*)<\/A>/ig;  
```

kan gebruikt worden om de link te herkennen.

**Comment by torrie** [comment]
Dan moet er wel gekeken worden of de link van de spotter is. Anders krijg je van die lui die gaan trollen, en nzbs gaan overschrijven. Ik weet niet in hoeverre de afzender verifieerbaar is?

Daarnaast ondermijn je het doel van de "encrypted" links, namelijk het moeilijk maken voor botjes om een nzb op te halen. Als er een standaard manier is om de nzb op te halen, word dit vroeg of laat gebruikt om posts te wisten van servers.
