### ISSUE TITLE
Missing refresh date and time in header

### ISSUE THREAD

**Issue by jacveld** [spotnet/spotnet#45]
![afbeelding](https://user-images.githubusercontent.com/9588506/50332001-0ea03f80-0501-11e9-9bc0-1d8c5d278441.png)
I would appreciate when you can see the refresh date and time.
At this moment you see in the "age" column today, yesterday and you cannot relate this with the refresh date !!

**Comment by mesa57** [comment]
Refresh of what ? Spots do not have a refresh date ....

**Comment by jacveld** [comment]
![afbeelding](https://user-images.githubusercontent.com/9588506/50340591-e245ec80-051b-11e9-8ee8-b5da72126fc5.png)
After clicking the refresh button you should get the refresh date and time on the same line (on top).
Than you can relate the "leeftijd" column with the refresh date.

I hope this is clear now to you.

regards,
Jacques

**Comment by mesa57** [comment]
I will put it on the wish list.
