### ISSUE TITLE
Error with Spotnet (Classic) 1.9.0.5

### ISSUE THREAD

**Issue by scifimollex** [spotnet/spotnet#46]
The last 4 weeks I have to start Spotnet (Classic) 1.9.0.5 twice before to be able to download a file.

The 1e time, after selecting an itim, a new window opens without anything in it. When I close Spotnet (Classic) 1.9.0.5 I get a message with a fatal error, see attachment.

[Snap2.pdf](https://github.com/spotnet/spotnet/files/4597814/Snap2.pdf)

When I start Spotnet (Classic) 1.9.0.5 again I can continue.

What am I doing wrong?

**Comment by mesa57** [comment]
Could please specify : 
- Which OS and version you are running ?
- If IE11 is installed ?
- Which version(s) of .net is installed.

Then we can see if we can reproduce the error.

**Comment by scifimollex** [comment]
Windows 10 Pro, Version 1909, build 18363.693.
Installed is Edge.
I am not aware of any .net version, or I do not know.

Attached file is the 1e msg (Snap1) and after that the 2e, you already have (Snap2).
[Snap1.pdf](https://github.com/spotnet/spotnet/files/4598532/Snap1.pdf)

Is this what you asked for?

**Comment by scifimollex** [comment]
Sorry, see attached file (Snap3)

[Snap3.pdf](https://github.com/spotnet/spotnet/files/4598555/Snap3.pdf)

**Comment by mesa57** [comment]
Ok, I will see if I can find some time to test on W10 pro 1909
Anyway, it is an internal .net error. Not caused by spotnet code.
It tries to render some media (image ?) and then fails.
Is this with all spots ???

**Comment by scifimollex** [comment]
[Snap3.pdf](https://github.com/spotnet/spotnet/files/4598903/Snap3.pdf)
[Snap2.pdf](https://github.com/spotnet/spotnet/files/4598904/Snap2.pdf)
[Snap1.pdf](https://github.com/spotnet/spotnet/files/4598905/Snap1.pdf)
[Snap5.pdf](https://github.com/spotnet/spotnet/files/4598906/Snap5.pdf)
[Snap4.pdf](https://github.com/spotnet/spotnet/files/4598907/Snap4.pdf)

It does not maater which spot, all.

All Snaps (in order) shows what happens.

**Comment by scifimollex** [comment]
After restart (snap 4 and 5), everything works OK.

**Comment by mesa57** [comment]
At this moment I can only report that on W10 1909 Enterprise (18363.778) it works fine.
